name = "api-interceptor"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV Namespaces
[[kv_namespaces]]
binding = "INTERCEPTORS"
id = "YOUR_INTERCEPTORS_KV_ID"  # Replace with the ID from the create command

[[kv_namespaces]]
binding = "REQUESTS"
id = "YOUR_REQUESTS_KV_ID"  # Replace with the ID from the create command

# Durable Objects
[[durable_objects.bindings]]
name = "WEBSOCKET_MANAGER"
class_name = "WebSocketManager"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketManager"]

# Routes (optional - if you want to handle specific domains)
# routes = [
#   { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ] 